baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'

[markup.goldmark.renderer]
  unsafe = true

show_recent_posts = false

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1


[[menu.main]]
  identifier = "about"
  name = "About Student"
  url = "/about/"
  weight = 2 


[[menu.main]]
  identifier = "articles"
  name = "Resources"
  url = "/articles/"
  weight = 3 